### PR TITLE
1007 Final Project by Shangying Jiang

### PR DESCRIPTION
**Pull request by sj2384**

### CODE REVIEW

**Comment by ds-ga-1007** [comment]
Please fix Conflicting files: .gitignore

**Comment by sj2384** [comment]
I just deleted .gitignore. Does this fix the conflict?

**Comment by ds-ga-1007** [comment]
it is still there.

**Comment by sj2384** [comment]
I don't quit know what happened, any advice? Can I delete my repo and restart things all over again?

**Comment by ds-ga-1007** [comment]
It still shows upon here, and I just checked, there is another file named this.

**Comment by sj2384** [comment]
The .gitignore file does not even exist in my repo. I really have no idea what is wrong.

**Comment by sj2384** [comment]
I created a .gitignore file in my repo and I copy & paste the content of .gitignore file in this repo to mine file. Looks like conflict solved.

**Pull request merged**
